"""v1.11.0.dev1 (Karaoke Tables)

Revision ID: 1fb6fa59d8c8
Revises: 2508b87106f3
Create Date: 2026-09-18 02:53:15.790048

"""

from collections.abc import Sequence
from enum import IntFlag, StrEnum
from logging import getLogger

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1fb6fa59d8c8"
down_revision: str | Sequence[str] | None = "2508b87106f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

log = getLogger("alembic.runtime.migration")


class UserPermission(IntFlag):
    NONE = 0

    JOIN_KARAOKE = 2**18
    VIEW_KARAOKE = 2**20


class UserType(StrEnum):
    student = "student"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "karaoke",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("min_point", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_karaoke_date"), "karaoke", ["date"], unique=False)
    op.create_index("ix_karaoke_date_time", "karaoke", ["date", "time"], unique=False)
    op.create_index(op.f("ix_karaoke_id"), "karaoke", ["id"], unique=False)
    op.create_table(
        "karaoke_party",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auction_id", sa.Integer(), nullable=False),
        sa.Column("leader_id", sa.Integer(), nullable=False),
        sa.Column("dispersed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["auction_id"], ["karaoke.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["leader_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_karaoke_auction_id_leader_id", "karaoke_party", ["auction_id", "leader_id"], unique=False)
    op.create_index(op.f("ix_karaoke_party_auction_id"), "karaoke_party", ["auction_id"], unique=False)
    op.create_index(op.f("ix_karaoke_party_id"), "karaoke_party", ["id"], unique=False)
    op.create_index(op.f("ix_karaoke_party_leader_id"), "karaoke_party", ["leader_id"], unique=False)
    op.create_table(
        "karaoke_bid",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auction_id", sa.Integer(), nullable=False),
        sa.Column("bidder_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["auction_id"], ["karaoke.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["bidder_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["karaoke_party.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_karaoke_auction_id_bidder_id", "karaoke_bid", ["auction_id", "bidder_id"], unique=False)
    op.create_index(op.f("ix_karaoke_bid_auction_id"), "karaoke_bid", ["auction_id"], unique=False)
    op.create_index(op.f("ix_karaoke_bid_id"), "karaoke_bid", ["id"], unique=False)
    op.create_table(
        "karaoke_member",
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("pending", sa.Boolean(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["party_id"], ["karaoke_party.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("party_id", "user_id"),
    )
    op.create_index(op.f("ix_karaoke_member_party_id"), "karaoke_member", ["party_id"], unique=False)
    op.create_index(op.f("ix_karaoke_member_user_id"), "karaoke_member", ["user_id"], unique=False)
    op.alter_column(
        "users",
        "history_type",
        existing_type=mysql.ENUM("teacher", "cafe", "food", "etc", "grant", "quest", "stamp", "stamp_bonus"),
        type_=sa.Enum(
            "teacher",
            "cafe",
            "food",
            "etc",
            "grant",
            "quest",
            "stamp",
            "stamp_bonus",
            "karaoke_bid",
            "karaoke_cancel",
            name="pointhistorytype",
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###

    # 기존 학생 계정은 이 마이그레이션 이전에 생성되어 노래방 관련 권한 비트가 없으므로,
    # 노래방 목록 조회/참여 권한을 켜서 즉시 사용할 수 있도록 한다.
    log.info("Proceeding with the Users karaoke permission migration")
    conn = op.get_bind()
    users = sa.table(
        "users",
        sa.column("id", sa.Integer),
        sa.column("permissions", sa.Integer),
        sa.column("type", sa.String(length=20)),
    )
    grant = UserPermission.JOIN_KARAOKE | UserPermission.VIEW_KARAOKE
    students = conn.execute(sa.select(users.c.id, users.c.permissions).where(users.c.type == UserType.student)).all()
    for i in students:
        conn.execute(users.update().where(users.c.id == i[0]).values(permissions=(UserPermission(i[1]) | grant).value))
    log.info("Users karaoke permission migration completed")


def downgrade() -> None:
    """Downgrade schema."""
    # 위에서 부여한 노래방 목록 조회/참여 권한 비트를 제거한다.
    log.info("Proceeding with the Users karaoke permission migration")
    conn = op.get_bind()
    users = sa.table(
        "users",
        sa.column("id", sa.Integer),
        sa.column("permissions", sa.Integer),
        sa.column("type", sa.String(length=20)),
    )
    revoke = UserPermission.JOIN_KARAOKE | UserPermission.VIEW_KARAOKE
    students = conn.execute(sa.select(users.c.id, users.c.permissions).where(users.c.type == UserType.student)).all()
    for i in students:
        conn.execute(
            users.update().where(users.c.id == i[0]).values(permissions=(UserPermission(i[1]) & ~revoke).value)
        )
    log.info("Users karaoke permission migration completed")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "history_type",
        existing_type=sa.Enum(
            "teacher",
            "cafe",
            "food",
            "etc",
            "grant",
            "quest",
            "stamp",
            "stamp_bonus",
            "karaoke_bid",
            "karaoke_cancel",
            name="pointhistorytype",
        ),
        type_=mysql.ENUM("teacher", "cafe", "food", "etc", "grant", "quest", "stamp", "stamp_bonus"),
        existing_nullable=True,
    )
    # MySQL은 FK 제약이 참조 중인 단일 컬럼 인덱스(ix_karaoke_member_user_id 등)를
    # 그 제약이 걸린 채로 개별 DROP INDEX 하는 것을 허용하지 않는다(에러 1553).
    # drop_table()이 해당 테이블의 인덱스/FK를 함께 정리해주므로 개별 drop_index 호출은
    # 제거하고 테이블 단위로만 드롭한다.
    op.drop_table("karaoke_member")
    op.drop_table("karaoke_bid")
    op.drop_table("karaoke_party")
    op.drop_table("karaoke")
    # ### end Alembic commands ###
