"""v1.8.0.dev4 (users.is_admin drop, users.permissions add)

Revision ID: 2508b87106f3
Revises: f91d6fc43436
Create Date: 2026-08-04 11:23:12.873678

"""

from collections.abc import Sequence
from enum import IntFlag, StrEnum
from logging import getLogger

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2508b87106f3"
down_revision: str | Sequence[str] | None = "f91d6fc43436"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

log = getLogger("alembic.runtime.migration")


class UserPermission(IntFlag):
    NONE = 0

    SEARCH_USER = 2**17
    DEDUCT_POINT = 2**0 | SEARCH_USER
    GRANT_POINT = 2**1 | SEARCH_USER
    NO_LIMIT_POINT = 2**2
    CREATE_QUEST = 2**3
    MANAGE_QUEST = 2**4
    GIVE_STAMP = 2**5 | SEARCH_USER
    VIEW_RANK = 2**6
    VIEW_POINT = 2**7
    VIEW_POINT_HISTORY = 2**8
    MANAGE_POST = 2**9
    CREATE_POST = 2**10
    VIEW_USER_POINT = 2**11 | SEARCH_USER
    JOIN_QUEST = 2**12
    MANAGE_USER = 2**13 | SEARCH_USER
    VIEW_POST = 2**14
    VIEW_STAMP = 2**15
    VIEW_QUEST = 2**16

    STUDENT = (
        VIEW_RANK
        | VIEW_POINT
        | VIEW_POINT_HISTORY
        | JOIN_QUEST
        | VIEW_POST
        | VIEW_STAMP
        | VIEW_QUEST
    )
    TEACHER = (
        GRANT_POINT
        | CREATE_QUEST
        | VIEW_RANK
        | VIEW_POINT
        | VIEW_POINT_HISTORY
        | VIEW_USER_POINT
        | VIEW_POST
        | VIEW_STAMP
    )
    ADMIN = MANAGE_USER | MANAGE_POST | MANAGE_QUEST | CREATE_POST


class UserType(StrEnum):
    student = "student"
    teacher = "teacher"
    service = "service"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("permissions", sa.Integer(), nullable=False))

    log.info("Proceeding with the Users permission migration")
    conn = op.get_bind()
    users = sa.table(
        "users",
        sa.column("id", sa.Integer),
        sa.column("permissions", sa.Integer),
        sa.column("type", sa.String(length=20)),
        sa.column("is_admin", mysql.TINYINT(display_width=1)),
    )
    before = conn.execute(sa.select(users.c.id, users.c.type, users.c.is_admin)).all()
    for i in before:
        permissions = UserPermission.NONE

        if i[1] == UserType.student:
            permissions |= UserPermission.STUDENT
        elif i[1] == UserType.teacher:
            permissions |= UserPermission.TEACHER
        elif i[1] == UserType.service:
            permissions |= UserPermission.DEDUCT_POINT

        if i[2]:
            permissions |= UserPermission.ADMIN

        conn.execute(
            users.update()
            .where(users.c.id == i[0])
            .values(permissions=permissions.value)
        )
    log.info("Users permission migration completed")

    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_admin",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
    )

    log.info("Proceeding with the Users permission migration")
    conn = op.get_bind()
    users = sa.table(
        "users",
        sa.column("id", sa.Integer),
        sa.column("permissions", sa.Integer),
        sa.column("type", sa.String(length=20)),
        sa.column("is_admin", mysql.TINYINT(display_width=1)),
    )
    before = conn.execute(sa.select(users.c.id, users.c.permissions)).all()
    for i in before:
        conn.execute(
            users.update()
            .where(users.c.id == i[0])
            .values(is_admin=UserPermission.ADMIN in UserPermission(i[1]))
        )
    log.info("Users permission migration completed")

    op.drop_column("users", "permissions")
    # ### end Alembic commands ###
