"""feat_karaoke_dev

Revision ID: 48514d794b29
Revises: 2508b87106f3
Create Date: 2026-09-02 16:29:16.054985

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "48514d794b29"
down_revision: str | Sequence[str] | None = "2508b87106f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "karaokeauction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=False),
        sa.Column("period", sa.String(length=10), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("min_bid", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("current_highest_bid_id", sa.Integer(), nullable=True),
        sa.Column("current_highest_bid_amount", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_karaokeauction_id"), "karaokeauction", ["id"], unique=False)
    op.create_index(op.f("ix_karaokeauction_target_date"), "karaokeauction", ["target_date"], unique=False)
    op.create_table(
        "karaokebid",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auction_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["auction_id"], ["karaokeauction.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_karaokebid_auction_id"), "karaokebid", ["auction_id"], unique=False)
    op.create_index(op.f("ix_karaokebid_id"), "karaokebid", ["id"], unique=False)
    op.create_index(op.f("ix_karaokebid_user_id"), "karaokebid", ["user_id"], unique=False)
    op.alter_column(
        "users",
        "history_type",
        existing_type=mysql.ENUM("teacher", "cafe", "food", "etc", "grant", "quest", "stamp", "stamp_bonus"),
        type_=sa.Enum(
            "teacher",
            "cafe",
            "food",
            "etc",
            "grant",
            "quest",
            "stamp",
            "stamp_bonus",
            "karaoke_bid",
            "karaoke_refund",
            name="pointhistorytype",
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "history_type",
        existing_type=sa.Enum(
            "teacher",
            "cafe",
            "food",
            "etc",
            "grant",
            "quest",
            "stamp",
            "stamp_bonus",
            "karaoke_bid",
            "karaoke_refund",
            name="pointhistorytype",
        ),
        type_=mysql.ENUM("teacher", "cafe", "food", "etc", "grant", "quest", "stamp", "stamp_bonus"),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_karaokebid_user_id"), table_name="karaokebid")
    op.drop_index(op.f("ix_karaokebid_id"), table_name="karaokebid")
    op.drop_index(op.f("ix_karaokebid_auction_id"), table_name="karaokebid")
    op.drop_table("karaokebid")
    op.drop_index(op.f("ix_karaokeauction_target_date"), table_name="karaokeauction")
    op.drop_index(op.f("ix_karaokeauction_id"), table_name="karaokeauction")
    op.drop_table("karaokeauction")
    # ### end Alembic commands ###
