"""fix_previous_quest_database

Revision ID: 4dddb3d41278
Revises: f91d6fc43436
Create Date: 2026-07-26 17:07:59.717707

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "4dddb3d41278"
down_revision: Union[str, Sequence[str], None] = "f91d6fc43436"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questcompletion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("quest_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["quest_id"], ["quests.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questcompletion_id"), "questcompletion", ["id"], unique=False)
    op.create_index(op.f("ix_questcompletion_quest_id"), "questcompletion", ["quest_id"], unique=False)
    op.create_index(op.f("ix_questcompletion_user_id"), "questcompletion", ["user_id"], unique=False)
    op.create_index("ix_questcompletion_user_id_quest_id", "questcompletion", ["user_id", "quest_id"], unique=False)
    op.add_column("quests", sa.Column("max_repeat", sa.Integer(), nullable=False))
    op.alter_column("quests", "end_date", existing_type=mysql.DATETIME(), nullable=False)
    op.create_index(op.f("ix_quests_end_date"), "quests", ["end_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quests_end_date"), table_name="quests")
    op.alter_column("quests", "end_date", existing_type=mysql.DATETIME(), nullable=True)
    op.drop_column("quests", "max_repeat")
    op.drop_index("ix_questcompletion_user_id_quest_id", table_name="questcompletion")
    op.drop_index(op.f("ix_questcompletion_user_id"), table_name="questcompletion")
    op.drop_index(op.f("ix_questcompletion_quest_id"), table_name="questcompletion")
    op.drop_index(op.f("ix_questcompletion_id"), table_name="questcompletion")
    op.drop_table("questcompletion")
    # ### end Alembic commands ###
