"""dev1

Revision ID: 66c183b28390
Revises: 2508b87106f3
Create Date: 2026-09-08 00:07:15.856860

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66c183b28390"
down_revision: str | Sequence[str] | None = "2508b87106f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "karaoke",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("time", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("min_point", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_karaoke_date"), "karaoke", ["date"], unique=False)
    op.create_index("ix_karaoke_date_time", "karaoke", ["date", "time"], unique=False)
    op.create_index(op.f("ix_karaoke_id"), "karaoke", ["id"], unique=False)
    op.create_table(
        "karaoke_party",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auction_id", sa.Integer(), nullable=False),
        sa.Column("leader_id", sa.Integer(), nullable=False),
        sa.Column("dispersed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["auction_id"], ["karaoke.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["leader_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_karaoke_auction_id_leader_id", "karaoke_party", ["auction_id", "leader_id"], unique=False)
    op.create_index(op.f("ix_karaoke_party_auction_id"), "karaoke_party", ["auction_id"], unique=False)
    op.create_index(op.f("ix_karaoke_party_id"), "karaoke_party", ["id"], unique=False)
    op.create_index(op.f("ix_karaoke_party_leader_id"), "karaoke_party", ["leader_id"], unique=False)
    op.create_table(
        "karaoke_bid",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auction_id", sa.Integer(), nullable=False),
        sa.Column("bidder_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["auction_id"], ["karaoke.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["bidder_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["karaoke_party.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_karaoke_auction_id_bidder_id", "karaoke_bid", ["auction_id", "bidder_id"], unique=False)
    op.create_index(op.f("ix_karaoke_bid_auction_id"), "karaoke_bid", ["auction_id"], unique=False)
    op.create_index(op.f("ix_karaoke_bid_id"), "karaoke_bid", ["id"], unique=False)
    op.create_table(
        "karaoke_member",
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("pending", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["party_id"], ["karaoke_party.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("party_id", "user_id"),
    )
    op.create_index(op.f("ix_karaoke_member_party_id"), "karaoke_member", ["party_id"], unique=False)
    op.create_index(op.f("ix_karaoke_member_user_id"), "karaoke_member", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_karaoke_member_user_id"), table_name="karaoke_member")
    op.drop_index(op.f("ix_karaoke_member_party_id"), table_name="karaoke_member")
    op.drop_table("karaoke_member")
    op.drop_index(op.f("ix_karaoke_bid_id"), table_name="karaoke_bid")
    op.drop_index(op.f("ix_karaoke_bid_auction_id"), table_name="karaoke_bid")
    op.drop_index("ix_karaoke_auction_id_bidder_id", table_name="karaoke_bid")
    op.drop_table("karaoke_bid")
    op.drop_index(op.f("ix_karaoke_party_leader_id"), table_name="karaoke_party")
    op.drop_index(op.f("ix_karaoke_party_id"), table_name="karaoke_party")
    op.drop_index(op.f("ix_karaoke_party_auction_id"), table_name="karaoke_party")
    op.drop_index("ix_karaoke_auction_id_leader_id", table_name="karaoke_party")
    op.drop_table("karaoke_party")
    op.drop_index(op.f("ix_karaoke_id"), table_name="karaoke")
    op.drop_index("ix_karaoke_date_time", table_name="karaoke")
    op.drop_index(op.f("ix_karaoke_date"), table_name="karaoke")
    op.drop_table("karaoke")
    # ### end Alembic commands ###
