"""v1.6.0 #1 (pointhistory.memo add)

Revision ID: 6949eef9a311
Revises: ecc0a589fbcd
Create Date: 2026-06-07 20:08:19.299153

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6949eef9a311"
down_revision: Union[str, Sequence[str], None] = "ecc0a589fbcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pointhistory",
        sa.Column("memo", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pointhistory", "memo")
    # ### end Alembic commands ###
