"""quest_accept_add

Revision ID: ae527c137361
Revises: 4dddb3d41278
Create Date: 2026-07-29 13:47:18.249861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ae527c137361"
down_revision: Union[str, Sequence[str], None] = "4dddb3d41278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("uq_questaccept_user_quest"), table_name="questaccept")
    op.create_index(op.f("ix_questaccept_id"), "questaccept", ["id"], unique=False)
    op.create_index(op.f("ix_questaccept_quest_id"), "questaccept", ["quest_id"], unique=False)
    op.create_index(op.f("ix_questaccept_user_id"), "questaccept", ["user_id"], unique=False)
    op.create_index("ix_questaccept_user_id_quest_id", "questaccept", ["user_id", "quest_id"], unique=False)
    op.drop_column("quests", "max_repeat")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quests", sa.Column("max_repeat", mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index("ix_questaccept_user_id_quest_id", table_name="questaccept")
    op.drop_index(op.f("ix_questaccept_user_id"), table_name="questaccept")
    op.drop_index(op.f("ix_questaccept_quest_id"), table_name="questaccept")
    op.drop_index(op.f("ix_questaccept_id"), table_name="questaccept")
    op.create_index(op.f("uq_questaccept_user_quest"), "questaccept", ["user_id", "quest_id"], unique=True)
    # ### end Alembic commands ###
