"""empty message

Revision ID: b1093dc70b41
Revises: 7c97ddba854b
Create Date: 2026-03-24 15:31:08.577916

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1093dc70b41"
down_revision: Union[str, Sequence[str], None] = "7c97ddba854b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pointhistory", sa.Column("type", sa.Enum("teacher", "cafe", "food", name="pointhistorytype"), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pointhistory", "type")
    # ### end Alembic commands ###
