"""v1.6.0 #2 (Quest, Posts tables add)

Revision ID: b4da6e37f3a6
Revises: 6949eef9a311
Create Date: 2026-06-23 10:14:46.308060

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4da6e37f3a6"
down_revision: str | Sequence[str] | None = "6949eef9a311"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_posts_author_id"), "posts", ["author_id"], unique=False)
    op.create_index(op.f("ix_posts_id"), "posts", ["id"], unique=False)
    op.create_table(
        "quest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reward", sa.Integer(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("max_repeat", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quest_author_id"), "quest", ["author_id"], unique=False)
    op.create_index(op.f("ix_quest_end_date"), "quest", ["end_date"], unique=False)
    op.create_index(op.f("ix_quest_id"), "quest", ["id"], unique=False)
    op.create_table(
        "postcontent",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_table(
        "questcompletion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("quest_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["quest_id"], ["quest.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_questcompletion_id"), "questcompletion", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_questcompletion_quest_id"),
        "questcompletion",
        ["quest_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_questcompletion_user_id"), "questcompletion", ["user_id"], unique=False
    )
    op.create_index(
        "ix_questcompletion_user_id_quest_id",
        "questcompletion",
        ["user_id", "quest_id"],
        unique=False,
    )
    op.alter_column(
        "pointhistory",
        "type",
        existing_type=mysql.ENUM("teacher", "cafe", "food", "etc", "grant"),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_pointhistory_id"), "pointhistory", ["id"], unique=False)
    op.create_index(
        op.f("ix_pointhistory_user_id"), "pointhistory", ["user_id"], unique=False
    )
    op.create_index(op.f("ix_users_type"), "users", ["type"], unique=False)
    op.create_index(
        op.f("ix_usersearch_user_id"), "usersearch", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usersearch_user_id"), table_name="usersearch")
    op.drop_index(op.f("ix_users_type"), table_name="users")
    op.drop_index(op.f("ix_pointhistory_user_id"), table_name="pointhistory")
    op.drop_index(op.f("ix_pointhistory_id"), table_name="pointhistory")
    op.alter_column(
        "pointhistory",
        "type",
        existing_type=sa.String(length=20),
        type_=mysql.ENUM("teacher", "cafe", "food", "etc", "grant"),
        existing_nullable=True,
    )
    op.drop_index("ix_questcompletion_user_id_quest_id", table_name="questcompletion")
    op.drop_index(op.f("ix_questcompletion_user_id"), table_name="questcompletion")
    op.drop_index(op.f("ix_questcompletion_quest_id"), table_name="questcompletion")
    op.drop_index(op.f("ix_questcompletion_id"), table_name="questcompletion")
    op.drop_table("questcompletion")
    op.drop_table("postcontent")
    op.drop_index(op.f("ix_quest_id"), table_name="quest")
    op.drop_index(op.f("ix_quest_end_date"), table_name="quest")
    op.drop_index(op.f("ix_quest_author_id"), table_name="quest")
    op.drop_table("quest")
    op.drop_index(op.f("ix_posts_id"), table_name="posts")
    op.drop_index(op.f("ix_posts_author_id"), table_name="posts")
    op.drop_table("posts")
    # ### end Alembic commands ###
