"""v1.8.0 #2 (Stamps tables add)

Revision ID: baaa7b1aacf8
Revises: d6cf30df9927
Create Date: 2026-07-12 23:03:58.904042

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "baaa7b1aacf8"
down_revision: str | Sequence[str] | None = "d6cf30df9927"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stamps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "stamp_type",
            sa.Enum(
                "BOOTH_1",
                "BOOTH_2",
                "BOOTH_3",
                "BOOTH_4",
                "BOOTH_5",
                "BOOTH_6",
                "BOOTH_7",
                "BOOTH_8",
                "BOOTH_9",
                "BOOTH_10",
                "BOOTH_11",
                "BOOTH_12",
                "BOOTH_13",
                "BOOTH_14",
                "BOOTH_15",
                "BOOTH_16",
                "BOOTH_17",
                name="stamptype",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stamps_user_id"), "stamps", ["user_id"], unique=False)
    op.alter_column(
        "users",
        "history_type",
        existing_type=mysql.ENUM("teacher", "cafe", "food", "etc", "grant"),
        type_=sa.Enum(
            "teacher", "cafe", "food", "etc", "grant", "quest", "stamp", "stamp_bonus", name="pointhistorytype"
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "history_type",
        existing_type=sa.Enum(
            "teacher", "cafe", "food", "etc", "grant", "quest", "stamp", "stamp_bonus", name="pointhistorytype"
        ),
        type_=mysql.ENUM("teacher", "cafe", "food", "etc", "grant"),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_stamps_user_id"), table_name="stamps")
    op.drop_table("stamps")
    # ### end Alembic commands ###
