"""v1.8.0 #1 (Quest to Quests name change)

Revision ID: d6cf30df9927
Revises: b4da6e37f3a6
Create Date: 2026-07-12 19:00:53.459925

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "d6cf30df9927"
down_revision: Union[str, Sequence[str], None] = "b4da6e37f3a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reward", sa.Integer(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("max_repeat", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quests_author_id"), "quests", ["author_id"], unique=False)
    op.create_index(op.f("ix_quests_end_date"), "quests", ["end_date"], unique=False)
    op.create_index(op.f("ix_quests_id"), "quests", ["id"], unique=False)

    op.drop_constraint(op.f("questcompletion_ibfk_1"), "questcompletion", type_="foreignkey")
    op.drop_constraint(op.f("quest_ibfk_1"), "quest", type_="foreignkey")
    op.drop_index(op.f("ix_quest_author_id"), table_name="quest")
    op.drop_index(op.f("ix_quest_end_date"), table_name="quest")
    op.drop_index(op.f("ix_quest_id"), table_name="quest")
    op.drop_table("quest")
    op.create_foreign_key(None, "questcompletion", "quests", ["quest_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "questcompletion", type_="foreignkey")
    op.create_foreign_key(
        op.f("questcompletion_ibfk_1"), "questcompletion", "quest", ["quest_id"], ["id"], ondelete="CASCADE"
    )
    op.create_table(
        "quest",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("description", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("reward", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("end_date", mysql.DATETIME(), nullable=False),
        sa.Column("max_repeat", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", mysql.DATETIME(), server_default=sa.text("(now())"), nullable=True),
        sa.Column("author_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("quest_ibfk_1"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(op.f("ix_quest_id"), "quest", ["id"], unique=False)
    op.create_index(op.f("ix_quest_end_date"), "quest", ["end_date"], unique=False)
    op.create_index(op.f("ix_quest_author_id"), "quest", ["author_id"], unique=False)
    op.drop_index(op.f("ix_quests_id"), table_name="quests")
    op.drop_index(op.f("ix_quests_end_date"), table_name="quests")
    op.drop_index(op.f("ix_quests_author_id"), table_name="quests")
    op.drop_table("quests")
    # ### end Alembic commands ###
