"""empty message

Revision ID: d7704d2ea4c0
Revises: b1093dc70b41
Create Date: 2026-03-24 20:15:23.570979

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d7704d2ea4c0"
down_revision: Union[str, Sequence[str], None] = "b1093dc70b41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("history_type", sa.Enum("teacher", "cafe", "food", name="pointhistorytype"), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "history_type")
    # ### end Alembic commands ###
