"""users.permissions

Revision ID: e23289f09926
Revises: f91d6fc43436
Create Date: 2026-07-15 01:33:41.119254

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "e23289f09926"
down_revision: Union[str, Sequence[str], None] = "f91d6fc43436"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("permissions", sa.Integer(), nullable=False))
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column("users", "permissions")
    # ### end Alembic commands ###
