"""v1.3.0 (users.total_point add)

Revision ID: ecc0a589fbcd
Revises: 38c026e839e6
Create Date: 2026-05-20 17:40:25.394554

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ecc0a589fbcd"
down_revision: str | Sequence[str] | None = "38c026e839e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("total_point", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "total_point")
    # ### end Alembic commands ###
