"""v1.8.0 #3 (stamps.stamp_type type change)

Revision ID: f91d6fc43436
Revises: baaa7b1aacf8
Create Date: 2026-07-13 23:07:46.385352WW

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f91d6fc43436"
down_revision: Union[str, Sequence[str], None] = "baaa7b1aacf8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stamps",
        "stamp_type",
        existing_type=mysql.ENUM(
            "BOOTH_1",
            "BOOTH_2",
            "BOOTH_3",
            "BOOTH_4",
            "BOOTH_5",
            "BOOTH_6",
            "BOOTH_7",
            "BOOTH_8",
            "BOOTH_9",
            "BOOTH_10",
            "BOOTH_11",
            "BOOTH_12",
            "BOOTH_13",
            "BOOTH_14",
            "BOOTH_15",
            "BOOTH_16",
            "BOOTH_17",
        ),
        type_=sa.String(length=20),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "stamps",
        "stamp_type",
        existing_type=sa.String(length=20),
        type_=mysql.ENUM(
            "BOOTH_1",
            "BOOTH_2",
            "BOOTH_3",
            "BOOTH_4",
            "BOOTH_5",
            "BOOTH_6",
            "BOOTH_7",
            "BOOTH_8",
            "BOOTH_9",
            "BOOTH_10",
            "BOOTH_11",
            "BOOTH_12",
            "BOOTH_13",
            "BOOTH_14",
            "BOOTH_15",
            "BOOTH_16",
            "BOOTH_17",
        ),
        nullable=False,
    )
    # ### end Alembic commands ###
